@startuml System_Architecture
!define DATABASE database
!define MOBILE node

skinparam packageStyle rectangle
skinparam arrowColor #333333
skinparam nodesep 100

package "Mobile Client Apps" {
  MOBILE "Android Client" as android
  MOBILE "iOS Client" as ios
}

package "System Administration" {
  MOBILE "Web Browser" as adminBrowser
}

cloud "Cloud Infrastructure" {
  [API Gateway] as gateway

  package "Microservices" {
    package "Parking " as parkingServicePkg {
      [Parking Service] as parkingService
      DATABASE "Parking DB" as parkingDB
    }

    package "Credit" as creditServicePkg {
      [Credit Service] as creditService
      DATABASE "Credit DB" as creditDB
    }

    package "Authentication" as authServicePkg {
      [Authentication Service] as authService
      DATABASE "Auth DB" as authDB
    }

  }
}

cloud "Monitoring Tools" {
  package "Uptime Monitor" as uptimeMonitorServicePkg {
    [Uptime Monitor Service] as uptimeMonitorService
    DATABASE "Uptime DB" as uptimeDB
  }
}

/'Clients to API Gateway'/
ios <--> gateway
android <--> gateway
adminBrowser <--> uptimeMonitorService

/'API Gateway to services'/
gateway <--> authService
gateway <--> creditService
gateway <--> parkingService
gateway <--> uptimeMonitorService

/'Services to their databases'/
authService <--> authDB
creditService <--> creditDB
parkingService <--> parkingDB
uptimeMonitorService <--> uptimeDB
@enduml